apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: luna-contacts
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/dariabrazhnyksuisse/lunaContacts.git
    targetRevision: main # not HEAD
    path: k8s # where deployment.yaml & service.yaml are
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true

      selfHeal: true
